spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestion-ressources?createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MariaDBDialect
    # show-sql: true
  data:
    rest:
      base-path: /
      default-media-type: application/json
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://localhost:8080/realms/marsa_maroc_realm"

server:
  port: 8088
